export type RootStackParamList = {
    Splash: undefined;
    Onboarding: undefined;
    SignUp: undefined;
    SignIn: undefined;
    ProfileCompletion: undefined;
    AuthSuccess: undefined;
    Home: undefined;
    Search: undefined;
    HomeTab: undefined;
    Settings: undefined;
    ProfileTab: undefined;
    SignUpOptions: undefined;
    SignUpForm: undefined;
    ProfileSetup: undefined;
    ProfilePicture: undefined;
    AppSelection: undefined;
    CategorySelection: undefined;
    SetupSuccess: undefined;
    Notifications: undefined;
}; 